{% set name = "chemplot" %}
{% set version = "1.0.0" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: "https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz"
  sha256: abd20750b3a75e657461598dadc3d4d4aa2470febb571810c593ff4b0d18920b

build:
  number: 2
  noarch: python
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  build:
    - python
    - setuptools
    - rdkit
  run:
    - python
    - rdkit
    - pandas >=1.1.3
    - numpy >=1.19.2
    - matplotlib >=3.3.2
    - seaborn >=0.11.1
    - umap-learn >=0.5.1
    - scikit-learn >=0.23.2
    - bokeh >=2.2.3
    - scipy >=1.5.2
    - mordred >=1.2.0
    - networkx >=2.5

about:
  home: https://github.com/mcsorkun/ChemPlot
  license: BSD-3-Clause License
  license_family: BSD
  license_file: LICENSE
  summary: "A python library for chemical space visualization."

  description: |
    In the last decades, Machine Learning (ML) applications have had a great impact on molecular and 
    material science. However, every ML model requires a definition of its applicability domain. Chemplot 
    is a python library for chemical space visualization that allows users to plot the chemical space of 
    their datasets. Chemplot contains smart algorithms behind which uses both structural and tailored 
    similarity. Moreover, it is easy to use even for non-experts.
  doc_url: https://chemplot.readthedocs.io/en/latest/
  dev_url: https://github.com/mcsorkun/ChemPlot 

extra:
  recipe-maintainers:
    - Dajt Mullaj 
    - Murat Cihan Sorkun